### PR TITLE
Parallel implementation of get_cpds()

### PR DESCRIPTION
**Pull request by khalibartan**
@ankurankan You can take a look at this, though implementation isn't that good, but gets work done in time.

### CODE REVIEW

**Comment by khalibartan** [comment]
@ankurankan Why coverage has decreased, It shows that call hasn't been made to search_cpds . Is this because the function was being run in pool

**Comment by khalibartan** [comment]
@ankurankan Can you suggest me a way on how to terminate the pool. I just ran the code and found pools are still active in the background, searched for solutions but couldn't find one.

**Comment by ankurankan** [comment]
@khalibartan Have a look at joblib (https://pypi.python.org/pypi/joblib). It's much simpler to work with. And also add an optional parameter `n_jobs` in the methods so that the user can specify on how many cores does he want to run it on.

**Comment by khalibartan** [comment]
@ankurankan I'll look into it, but should I send a new patch because using joblib will add an extra dependency .

**Comment by ankurankan** [comment]
@khalibartan Yeah you can.

**Comment by khalibartan** [comment]
@ankurankan Cool then, will send a patch.

**Comment by ankurankan** [comment]
@khalibartan I am closing this as you will be sending a new PR

**Pull request closed without merging**
