### PR TITLE
Added Structural Hamming metric

### PR DESCRIPTION
**Pull request by Nimish-4**
### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.

### Issue number(s) that this pull request fixes
- Fixes #

### List of changes to the codebase in this pull request
- 
-
-

### CODE REVIEW

**Comment by ankurankan** [comment]
@Nimish-4 The code formatting checks are failing. You can run black on the file to fix it:
```bash
black pgmpy/pgmpy/metrics/metrics.py
```

I would also suggest installing pre-commit hooks to automatically detect and fix these when creating commits. You can run the following from the pgmpy directory to install the hooks:
```bash
pip install pre-commit
pre-commit install
```

**Comment by Nimish-4** [comment]
@ankurankan I will make the change. I ran the command and it has reformatted the code.

**Comment by ankurankan** [comment]
@Nimish-4 BTW you don't need to close the PRs. You can keep pushing any new changes on the same branch, and it would update the PR.

**Comment by Nimish-4** [comment]
@ankurankan I will keep that in mind from now on.

**Pull request closed without merging**
