### PR TITLE
issue #247 improved ModelError

### PR DESCRIPTION
**Pull request by yashu-seth**
@ankurankan 
Please look into it.
Please suggest changes if required.
If its fine I will edit the other models as well.

### CODE REVIEW

**Comment by ankurankan** [comment]
@yashu-seth I think this issue has already been fixed since `model.check_model` will raise the appropriate exceptions. You can check once if something is missing in `check_model`. 

And also please let us know once before you start working on some issue so that you don't spend time on working on something that has already been fixed or not relevant anymore.

**Comment by yashu-seth** [comment]
I think the check_model function should only return True or False and there should be a separate function to get the type of error because there could be cases where the ValueError raised has to be displayed along with some other error message. Like in this case I think ModelError should also be displayed. 
Please tell me if the changes are unnecessary and I will focus on a different issue. 
I will let you know before starting to work on an issue in the future.

**Comment by ankurankan** [comment]
@yashu-seth  I don't think that there is much need of raising model error when check_model is already giving enough information for debugging. Also adding a new method will does almost the same thing will lead to code repetition.

**Comment by yashu-seth** [comment]
Okay. The issue got me thinking over it in the first place. I will definitely notify you before starting on an issue from now on.

**Pull request closed without merging**
