### PR TITLE
Adds Markov Blanket Property to Bayesian Models

### PR DESCRIPTION
**Pull request by harishkashyap**
#### Changes
- Adds Markov Blanket Property to Bayesian Models.

### CODE REVIEW

**Comment by harishkashyap** [comment]
@ankurankan how do i expedite this? We are creating curriculum for workshops using pgmpy. There are hoard of examples that might be useful to users of this repo. However, we need more properties to get into this ASAP. Let me know how/what I can do to get this in? Let me know if I need to hop on a call for this.

**Comment by ankurankan** [comment]
@harishkashyap Sorry for the late reply. I will get this merged ASAP.

**Comment by ankurankan** [comment]
@harishkashyap Could you create a new PR for this without merging `dev` into your branch? Merging creates a non-linear git history, therefore rebasing is a better option in such situations. I would also like to have few changes in your code: 
1. The `markov_blanket` method can be much more efficient. 
2. I would like to have the name `get_markov_blanket` instead of `markov_blanket` to have uniformity across pgmpy.
3. The tests for `markov_blanket` are wrong. 

I have made these changes in my branch, you can have a look at it here: https://github.com/ankurankan/pgmpy/blob/pr/957/pgmpy/models/BayesianModel.py and https://github.com/ankurankan/pgmpy/blob/pr/957/pgmpy/tests/test_models/test_BayesianModel.py

**Review by ankurankan — CHANGES_REQUESTED** [review]
Refer to last comment.

**Comment by harishkashyap** [comment]
@ankurankan, I have made the changes as you suggested and put up another PR on a different branch. I wanted to use get_ method but had changed to markov_model based on this: (http://pgmpy.org/_modules/pgmpy/models/MarkovModel.html) to maintain uniformity.

**Comment by ankurankan** [comment]
Closing this since duplicate of #959

**Pull request closed without merging**
