### PR TITLE
Fix #704

### LINKED ISSUE #704: GibbsSampling on BayesianModel not working
Hi,
I added to the example code for GibbsSampling one more node connection 'doc', and it fails,
The following code produce error:

```
from pgmpy.factors import TabularCPD
from pgmpy.models import BayesianModel
intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2,  [[0.95, 0.2,0.95, 0.2], [0.05, 0.8,0.95, 0.2]], evidence=['intel','doc'], evidence_card=[2,2])
doc_cpd = TabularCPD('doc', 2, [[0.7], [0.3]])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat','doc'])
student.add_edge('intel', 'sat')
student.add_edge('doc', 'sat')
student.add_cpds(intel_cpd, sat_cpd,doc_cpd)

from pgmpy.inference import GibbsSampling
gibbs_chain = GibbsSampling(student)

t= gibbs_chain.sample(size=1000)

```

The error:

```
Traceback (most recent call last):
  File "C:\projects\pgm\Random Generation of BN\test gibsSampling.py", line 13, in <module>
    gibbs_chain = GibbsSampling(student)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 253, in __init__
    self._get_kernel_from_bayesian_model(model)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 280, in _get_kernel_from_bayesian_model
    prod_cpd_reduced = prod_cpd.reduce(states, inplace=False)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\factors\CPD.py", line 335, in reduce
    raise ValueError("Reduce not allowed on the variable on which CPD is defined")
ValueError: Reduce not allowed on the variable on which CPD is defined

```

### PR DESCRIPTION
**Pull request by huangy6**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Changes
Please list the proposed changes in this pull request.
- Fix GibbsSampling in a BayesianModel by casting CPDs in the transition model to generic factors
- Store samples as tuples since numpy arrays cannot nest

💔Thank you!

### CODE REVIEW

**Comment by ankurankan** [comment]
@huangy6 Thanks for the PR. Could you please rebase your branch to the latest dev?

**Review by ankurankan — APPROVED** [review]
Waiting for rebase.

**Comment by ankurankan** [comment]
@huangy6 I was suggesting to rebase instead of merge to avoid having merge commits in dev. Could you please revert your last merge commit and rebase dev on your branch?

**Review by khalibartan — CHANGES_REQUESTED** [review]
@huangy6 Can you please add the test case to verify changes? I guess a simple test case could be the example on which it was failing earlier.

**Comment by ankurankan** [comment]
Alreayd fixed.

**Pull request closed without merging**
