### PR TITLE
modified:   pgmpy/models/NoisyOrModel.py Refactored code to use pgmpy.base.DirectedGraph

### PR DESCRIPTION
**Pull request by gokul-uf**
Minor changes to resolve [issue #239]

### CODE REVIEW

**Comment by gokul-uf** [comment]
All the current methods use numpy so refactoring wasn't difficult, also why is there no issue opened to implement out_prob( )? Can I work on this?

**Comment by ankurankan** [comment]
@gokul-uf Go ahead. FYI our implementation is not the simple NoisyOr but as mentioned in: http://xenon.stanford.edu/~srinivas/research/6-UAI93-Srinivas-Generalization-of-Noisy-Or.pdf

**Comment by ankurankan** [comment]
@gokul-uf Also could you please fix the tests so that I could merge this.

**Comment by ankurankan** [comment]
@gokul-uf Please write tests for these so I could merge it.

**Comment by gokul-uf** [comment]
@ankurankan there won't be any need for new test cases as it is essentially doing the same thing albeit in a bit more optimized manner

**Comment by ankurankan** [comment]
@gokul-uf I am not talking about new test cases. Right now there are no tests for this. So whatever features are implemented please make sure that there are tests for them
.

**Comment by abinashpanda** [comment]
@gokul-uf Please look into @landscape-bot messages. There is one PEP8 error in your code.

**Comment by gokul-uf** [comment]
@ankurankan Now that we know `add_variables` is buggy [issue #319] writing unit tests to test `add_variables` and accepting that PR would break the repo, shall I leave out those tests for now?

**Comment by ankurankan** [comment]
@gokul-uf Could you fix this PR?

**Pull request closed without merging**
