### PR TITLE
changed to_factor_graph() function in MarkovModel.py

### PR DESCRIPTION
**Pull request by VSSILPA**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Changes
factor_node change to factor in MarkovModel.py line 295.

💔Thank you!

### CODE REVIEW

**Comment by khalibartan** [comment]
@VSSILPA Why did you close this pull request?

**Comment by VSSILPA** [comment]
Sorry, forgot to add test cases.

**Comment by khalibartan** [comment]
@VSSILPA There is no need to close the PR. You can always add commit incrementally and it is also the recommended way.

**Comment by VSSILPA** [comment]
Ok, thanks for letting me know.

**Pull request closed without merging**
