### PR TITLE
Fixed typo in examples and fleshed out

### PR DESCRIPTION
**Pull request by loudly-soft**
@ankurankan I noticed you added a few more examples so I updated mine as well.  Cheers.

### CODE REVIEW

**Comment by ankurankan** [comment]
@loudly-soft Thanks for the PR. In the changes, I see that you have deleted the `Learning Parameters in Discrete Bayesian Networks` notebook (maybe by accident)? Could you please it back?

**Comment by loudly-soft** [comment]
@ankurankan Oops, sorry, dunno what happened.  Bringing it back from the dead as we speak.

**Comment by loudly-soft** [comment]
@ankurankan  I think you might enjoy [this](https://loudly-soft.blogspot.com/2020/08/classification-with-tree-augmented.html).  :)

**Comment by ankurankan** [comment]
@loudly-soft The blogpost looks great. Would you like to link that in the example notebook? I think it might help users as it is more descriptive than the example notebook.

**Pull request merged**
