### PR TITLE
bug fix: KeyError in BayesianModel.get_markov_blanket method #1293

### PR DESCRIPTION
**Pull request by Lostefra**
Bug fix for KeyError in BayesianModel.get_markov_blanket method pgmpy#1293

### CODE REVIEW

**Comment by ankurankan** [comment]
@Lostefra Thanks for the PR. Could you please also add a test case ( in this file: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_models/test_BayesianModel.py) that would fail with the previous codebase and get fixed with the changes? The example that you had given in the issue would also work.

**Comment by Lostefra** [comment]
@ankurankan Ok, done it. I am not sure what is wrong with the checks

**Comment by ankurankan** [comment]
@Lostefra It's because of code formatting and a minor error. I have pushed a commit fixing both. Everything else looks good. Thanks for the fix.

**Comment by Lostefra** [comment]
@ankurankan Ok, seen. It is my first time ever for a PR and I never really worked with python unittest before, I am sure you can understand :) 

Cheers!

**Pull request merged**
