### PR TITLE
issue#722 changed get_cpd in TabularCPD to get_values

### PR DESCRIPTION
**Pull request by sahithikilaru**
In reference to issue #722: get_cpd in TabularCPD doesn't seem to be a suitable name for the method.

### CODE REVIEW

**Comment by khalibartan** [comment]
@sahithikilaru `variable_cpd` doesn't seem to be a good name either ( to me). Can you think of some alternate name?

**Comment by sahithikilaru** [comment]
@khalibartan the method get_cpd returns a CPD in the form of an array pertaining to the given "variable" regardless of the cardinality of its parents. Hence the name variable_cpd.

**Comment by khalibartan** [comment]
@sahithikilaru Okay, this some what specifies the context but still I'm not liking it. IMO it is not much better than `get_cpd`. The method is returning an array not a cpd, for me the cpd in the end of name doesn't make much sense.
@ankurankan @yashu-seth Views?

**Comment by sahithikilaru** [comment]
@khalibartan I agree. The "cpd" part does not sound quite right. How about 'get_values' instead?

**Comment by ankurankan** [comment]
@khalibartan @sahithikilaru `get_values` makes more sense to me.

**Comment by khalibartan** [comment]
@sahithikilaru @ankurankan +1. @sahithikilaru Please make necessary changes.

**Comment by sahithikilaru** [comment]
I replaced variable_cpd with get_values and squashed the commits into one but the coverage (which previously remained the same and all checks had been successful) has now decreased.

**Comment by raghavg7796** [comment]
@ankurankan @sahithikilaru @khalibartan I think this will interfere with #814.

**Comment by khalibartan** [comment]
@raghavg7796 I think it will not, we can merge this pr straight away because there are no big changes and you can then accommodate the changes in your pr.

**Comment by sahithikilaru** [comment]
I have messed up my dev branch and commit history and I'm unable to work around it so I'm going to close this pr and send a new one soon for the same.

**Comment by sahithikilaru** [comment]
new pull request made

**Pull request closed without merging**
