### PR TITLE
Added wrapt.decorator to preserve documentation

### PR DESCRIPTION
**Pull request by raghavg7796**
Solving #773

### CODE REVIEW

**Comment by raghavg7796** [comment]
@ankurankan Tests are failing as they can't import wrapt. What should be done?

**Comment by yashu-seth** [comment]
@raghavg7796 I am not too sure if we would want to have an extra dependency for this. That is why we passed on the idea of using decorator module in the first place.
@ankurankan What do you think?

**Comment by raghavg7796** [comment]
I was too avoiding and tried to solved it using other methods like functools but I think we have to use dependencies for python2. Moreover @ankurankan suggested wrapt, so I think he will be OK with this.

**Comment by raghavg7796** [comment]
@yashu-seth @ankurankan Then we can just use the code of decorator in wrapt. Its a few lines of code(70 lines) and can be added in another module in utils.???

**Comment by ankurankan** [comment]
@yashu-seth @raghavg7796 I am fine adding a dependency for this. @raghavg7796 For travis to install wrapt you will need to add it to `requirements.txt` and `requirements-dev.txt`

**Comment by raghavg7796** [comment]
@ankurankan I added it to requirements and requirements-dev ... still not working

**Comment by yashu-seth** [comment]
@raghavg7796 Can you please also look into the decorator module and compare it with wrapt for our use case here.

**Comment by raghavg7796** [comment]
@yashu-seth I studied decorator module and founded it difficult to be used in case of class based decorators like ours. While wrapt is properly structured for bath class and function decorators.

**Pull request closed without merging**
