### PR TITLE
Optimize variable elimination

### PR DESCRIPTION
**Pull request by ankurankan**
Changes:
1. Adds elimination order 
2. Adds barren nodes 
3. Adds reduce over evidence
4. Changes the expected type of the evidence argument.
5. Remove node method in bayesian network

### CODE REVIEW

**Comment by ankurankan** [comment]
Depends on #516. Need to fix that to fix the tests.

**Comment by yashu-seth** [comment]
@ankurankan I was just going through the dev code for VariableElimination. If you want I can give you a hand on this or on PR #517. Please tell me if there are tests to be written or may be a particular problem that you feel I can look into.

**Comment by ankurankan** [comment]
@yashu-seth No, I just need to fix a few more things and this will be ready. Just not getting time :D

**Comment by khalibartan** [comment]
@ankurankan Status ?

**Comment by ankurankan** [comment]
@khalibartan I am waiting on this till I finish the support for continuous variables as this will be dependent on that.

**Pull request closed without merging**
