### PR TITLE
fixes BayesianModel.predict bug from issue #698

### PR DESCRIPTION
**Pull request by yashu-seth**
Refer #698 for details.
This is not ready for a merge. Work is still in progress.

### CODE REVIEW

**Comment by yashu-seth** [comment]
This is not ready for a merge. Work is still in progress.

**Comment by ankurankan** [comment]
@yashu-seth Please let me know when this is ready for review.

**Comment by yashu-seth** [comment]
@ankurankan I have fixed the bug described in #698. 
But currently for ```fit``` and ```predict``` method it is required that the data should be in string format. Should we leave it to the users to convert the input data into string by mentioning it in the docs and raising necessary type checks? Or should we internally convert the data into string format?

**Comment by yashu-seth** [comment]
@ankurankan What are your views on this?

**Comment by ankurankan** [comment]
@yashu-seth I really don't want any code related to state names in the general code base. That will just make the whole codebase confusing. Isn't there any other way to fix this ?

**Comment by yashu-seth** [comment]
@ankurankan The CPDs created using the fit method create state name dicts automatically. So for predict we need these state names. There is an internal call to ```Inference``` class in the predict method and therefore it need the state names dict as an input parameter. 

An another way would be to wrap the return value of the predict method. It returns a pandas data frame. This case does not exist in ```StateNameDecorator```, so it will have to be added. Since, currently pgmpy models do need a state name dict, a case has to be added in the state name decorator where it checks for a state name dict in the CPDs associated with the model as well.

But I feel the former method is better because anyway the ```predict``` method calls ```Inference.map_query``` which uses the state name functionality appropriately.

**Comment by ankurankan** [comment]
@yashu-seth Do we need to update some tests for this ?

**Comment by yashu-seth** [comment]
@ankurankan I have added some more tests for the ```predict``` method. This is ready for a review.

**Pull request merged**
