### PR TITLE
Overhaul of CI and setup infastructure

### PR DESCRIPTION
**Pull request by Erotemic**
As discussed in #1103 this PR is an overhaul of the setup, CI, and publishing system. 

### setup.py changes 

First, there are changes in `setup.py`. There were a few fields missing (long_description_content_type), the long_description was set to a url, but I actually included the text of the README.md file. I also changed the version such that it **statically** parsed the version from `pgmpy/__init__.py` instead of dynamically importing it and causing potential on-import side effects (not necessary here, but I find its good practice). I also included `install_requires` by parsing the requirements files. 

### requirements changes
The new requirements.txt lists all requirements, both runtime and testing. If you just want runtime dependencies do `pip install -r requirements/runtime.txt`. However, because these are registered with setup.py, you only need to `pip install .` in order to get everything for runtime. You can also `pip install .[all]` in order to install the entire package. 

### testing

So I did minor testing framework changes. First off I added a dependency on `pytest`, that is just the de-facto ways to run tests these days. Using `nose` is deprecated. I modified the README appropriately. I also added a `./run_tests.py` script, which should make things unambiguous. The `pytest.ini` currently disables doctests and xdoctest because those tests are failing, but by removing a comment we can re-enable them once they are working. 

### appveyor 

I really took a hammer to this file. Not 100% it will work yet, but I'll debug it and revert if necessary. At least in my experience you don't need to much to make a simple appveyor script work.

EDIT: to make this work I had to ensure that I was using the 64-bit Python executable and install torch using a special command, other than that there isn't anything special in the script.  

### travis.yml

This file actually has fewer change than it appears. Most of the bulk has in this file has to do with automatic GPG signing and publishing wheels. There is a `__heredoc__` section explaining how to encrypt your pypi/twine username/pass and gpg keys. The later section is the logic to decrypt them and run the publish.sh script which will build wheels and push them to pypi (if specified, otherwise it just builds wheels). There is also a big ugly block to download newer gpg binaries on travis, which will hopefully go away in a few years. 

Note, that I added the `black` linting check in the .travis.yml file, whereas previously it was in a separate script. 

### publish.sh

Without any args, this script just builds wheels. By specifying certain flags it will also gpg-sign those wheels and push them to pypi. This script can be run on the CI or on a local machine. 

### misc

I also 

* added a number-of-downloads badge to the README
* skipped test_MmhcEstimator.py explicitly 
* removed the ci folder as it is no longer used.

### notes 

I'm not sure if `ez_setup.py` is still required. I left it alone, but I'm not using it for anything and it looks like legacy easy-install stuff. If its not for conda we should remove it. (EDIT: I looked it up, it is a deprecated way to distribute python packages, so I removed it)

I don't have any experience publishing on conda, so whatever process you use for that will have to remain the same for now. IIUC, it just has to do with having a meta.yaml file. 

Other than that, let me know any thoughts or questions. This is a big PR, but all the concepts are pretty simple. I'm sure the first run will fail, so I'll make sure to get the dashboards green in the near future. 

I removed the leading "v" from `__version__` to comply with [PEP 386](https://www.python.org/dev/peps/pep-0386/).

### CODE REVIEW

**Comment by Erotemic** [comment]
So, it looks like this is currently passing. This branch could be merged as-is, but if you want to round it out by adding the appropriate secret variables to travis this is how you do it. 


First, install GPG, I'm going to assume you are on an Ubuntu 18.04 machine. 

```bash

# Install GPG
sudo apt-get install gnupg -y

# Create a GPG identity
# EDIT THIS EXPECT SCRIPT AS YOU SEE FIT. 
# WHEN YOU EXECUTE THE EXPECT SCRIPT THE SYSTEM KEYRING MAY ASK YOU TO ENTER A PASSWORD, LEAVE THIS BLANK. 

# Change the "1y" to 0 if you don't want the key to ever expire. 

    ##########
    # Generate a new GPG Key via `gpg --full-generate-key --expert`
    # Expect script to go through the interactive process of GPG selection.
    # Chooses ECC Curve 25519 cyphers, and expires after 1 year.
    expect -c '
spawn gpg --full-generate-key --expert
expect "Your selection? "
send "9\r";
expect "Your selection? "
send "1\r";
expect "Key is valid for? (0) "
send "1y\r"
expect "Is this correct? (y/N) "
send "y\r"
expect "Real name: "
send "ankurankan-CI-Key\r"
expect "Email address: "
send "ankurankan@gmail.com\r"
expect "Comment: "
send "This key is for signing releases on CI servers\r"
expect "Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? "
send "O\r"
interact
'
```

We have now created a GPG key, the next step is to upload the public key to a keyserver.

```bash
    
    #-----
    # Now ensure you have an IDENTIFIER environment variable set to reference your key
    IDENTIFIER="ankurankan-CI-Key" 
    KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
    echo "KEYID = $KEYID"

    ###########
    # Let the public know about your public key
    # Upload public key to the MIT server (not sure if this is the best server, but lets get it out there)
    gpg --send-keys --keyserver hkp://pgp.mit.edu $KEYID
    # Upload to a large keyserver pool
    gpg --send-keys --keyserver hkp://pool.sks-keyservers.net $KEYID

```

Now your GPG key is all setup, so now we follow the instructions in the `__heredoc__` in the new  .travis.yml file.

First ensure you have `TWINE_USERNAME` and `TWINE_PASSWORD` environment variables appropriately set. Also set another variable `CI_GITHUB_SECRET` to a random sequence of characters. I use a bash+python function to accomplish this. 

```
export TWINE_USERNAME=<SET THIS TO YOUR PYPI USERNAME>
export TWINE_PASSWORD=<SET THIS TO YOUR PYPI PASSWORD"

randpw(){ 
    __heredoc__="""
    Generate a random password

    References:
        https://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/
    """
    head -c${1:-128} /dev/random | sha512sum | python -c "import string, ubelt, sys; print(ubelt.hash_data(sys.stdin.read(), base=list(string.ascii_letters + string.digits)))"
}

export CI_GITHUB_SECRET="$(randpw)"
```

Now that you have your secrets as environment variables, we let travis know about them. 

```bash
        # First install the travis command line tool
        sudo apt install ruby ruby-dev -y
        sudo gem install travis

       # Next run the travis encrypt command to login. This must be done in the root of the pgmpy repo. 
       # The first time you run this it will ask if the repo is correct and may request credentials
        travis encrypt TWINE_USERNAME=$TWINE_USERNAME 
    
       # after authenticating via the first run, each of these commands
        travis encrypt TWINE_USERNAME=$TWINE_USERNAME 
        travis encrypt TWINE_PASSWORD=$TWINE_PASSWORD  
        travis encrypt CI_GITHUB_SECRET=$CI_GITHUB_SECRET
   
        # This will output stuff to the CLI and you have to manually add the  results to the `.travis.yml`. Replace the `- secure: "YOUR-SECRET1"` placeholders I put in there. You can copy paste the secure line as is, but you have to remember to prefix it with a "-" to ensure you use valid yaml. Note that the travis cli gives you an option to auto-add these variables to your .travis.yml script, but don't do this. This messes up the formatting of the file. Just do it manually, this is the last manual step.
```

Now we are finally finished with the manual work. The final step is to run this script, which encrypts your GPG keys and adds them to the "dev" folder in the pgmpy repo. 

```bash
        # HOW TO ENCRYPT YOUR SECRET GPG KEY
        IDENTIFIER="ankurankan-CI-Key" 
        KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
        echo "KEYID = $KEYID"

        # Export plaintext gpg public keys, private keys, and trust info
        mkdir -p dev
        gpg --armor --export-secret-keys $KEYID > dev/travis_secret_gpg_key.pgp
        gpg --armor --export $KEYID > dev/travis_public_gpg_key.pgp
        gpg --export-ownertrust > dev/gpg_owner_trust

        # Encrypt gpg keys and trust with CI secret
        TSP=$CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -e -a -in dev/travis_public_gpg_key.pgp > dev/travis_public_gpg_key.pgp.enc
        TSP=$CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -e -a -in dev/travis_secret_gpg_key.pgp > dev/travis_secret_gpg_key.pgp.enc
        TSP=$CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -e -a -in dev/gpg_owner_trust > dev/gpg_owner_trust.enc
        echo $KEYID > dev/public_gpg_key

        # Look at what we did, clean up, and add it to git
        ls dev/*.enc
        rm dev/gpg_owner_trust dev/*.pgp
        git status
        git add dev/*.enc
        git add dev/public_gpg_key

```

git commit and push. If these secret variables are correctly set in travis and in this repo, then the CI logs on travis will show that we signed with our gpg key successfully. However, it won't upload these wheels to pypi. 

It will only execute the `twine` command to upload to pypi if TravisCI runs on the release branch. I've handled this one of two ways in the past. The first way I merge master into release, tag release with the version and then push to github, which triggers the CI. I've been moving away from that in the past. Now, instead I tend to simply run `git push origin master:release`, which pushes the exact current state of master to release. It doesn't automatically do git tagging, but I'm working on that. In the case of pgmpy the command would be: `git push origin dev:release`, which would update the release branch to point at the latest dev. 

Ultimately, how releases work is pretty flexible. Choose your criterion for making a release and merge whatever that is into the release branch on github. The CI will take care of the rest. (Or note, that you can run the `./publish.sh` script on your machine manually if you don't want the CI taking care of releases).

**Comment by ankurankan** [comment]
@Erotemic Thanks a lot for this PR, it was much needed. I have added my GPG keys and everything seems to be working fine. Though I am not sure if I understand exactly how everything works now. My understanding right now is that we have now added my encrypted pypi credentials to travis.yml, and have given travis permission to sign the built wheels using my GPG keys. And when pushing to pypi travis decrypts my credentials and uses it to upload to pypi. Am I understanding it correctly? Also, in case if you know of any resources which could help me understand this, it would really help.

**Comment by Erotemic** [comment]
Your understanding is correct. I'll elaborate to help solidify it. 

We used the travis-client executable to encrypt your pypi credentials (TWINE_USERNAME and TWINE_PASSWORD) as well as an additional secret variable (CI_GITHUB_SECRET). By adding these as secret variables to your .travis.yml the CI server can decrypt and use these. Essentially the server will see plain text versions of these environment variables, and we use the pypi credentials directly. 

The CI_GITHUB_SECRET is slightly more complicated. The reason is the gpg private keys are too long to encrypt directly using travis. Instead we encrypt a shorter random password and use that as a secret to encrypt the gpg files manually. To do this we simply use openssl commands and pass that CI_GITHUB_SECRET as the encryption/decryption password. There is a way for travis-client to encrypt files directly, but I was never successful in getting it working, and its kinda cool/fun to do the encryption / decryption ourselves. 

Its not so much that you are giving travis permission to sign the keys (technically that is what you are doing). Instead, its that the CI server is able to see a plain-text gpg private key, so it can use the gpg executable to sign packages with that private key. Technically anyone with that private key would have "permission" to sign your packages. Signing a package (e.g. foo.whl) simply creates a signature file (foo.whl.asc) and you upload both of those files to pypi instead of just one. You can use the asc file with the gpg executable to verify that the package indeed was published by the person who owns the private key corresponding to the plain-text public key that lives in the dev/public_gpg_key file. 

So long story short, if you look in the `publish.sh` file, the key line of interest is 

```bash
twine upload --username $TWINE_USERNAME --password=$TWINE_PASSWORD --sign $WHEEL_PATH.asc $WHEEL_PATH
```

The TWINE_USERNAME and TWINE_PASSWORD exist as plain-text environment variables on the travis server, so those are used to authenticate with the pypi server. And the `$WHEEL_PATH.asc` file is the gpg signature that was signed with our private gpg key (which was decrypted using openssl and our CI_GITHUB_SECRET variable). 

I tend to keep notes on the references I came across while I was learning how to do all of this. I'll leave those here: 


Travis-client executable: 

* https://github.com/travis-ci/travis.rb

Python packaging: 

* https://realpython.com/pypi-publish-python-package/
* https://www.andreagrandi.it/2016/04/10/how-to-publish-a-python-package-to-pypi/
* https://packaging.python.org/tutorials/packaging-projects/#uploading-your-project-to-pypi

GPG References:

* http://www.koozie.org/blog/2014/07/migrating-gnupg-keys-from-one-computer-to-another/
* https://help.github.com/en/articles/signing-commits
* https://thoughtbot.com/blog/pgp-and-you
* https://python-security.readthedocs.io/packages.html
* https://github.com/cristal-ise/kernel/wiki/Maven-Deploy-Travis-GPG2
* https://gist.github.com/romen/b7bac24d679d91acabb27bfcdabbee01
* https://github.com/drduh/YubiKey-Guide

There isn't a single resource that I found that pulls all of this together. This is a process that I developed by stitching pieces of these resources together.

**Comment by ankurankan** [comment]
@Erotemic Thanks a lot for clarifying it, I think I understand the basic ideas now.

**Comment by ankurankan** [comment]
@Erotemic So, I was trying to make a release and push it to pypi but it fails to sign the built wheels on travis: https://travis-ci.org/pgmpy/pgmpy/jobs/640443537#L6088. Maybe I have missed adding something to the config file? I would really appreciate it if you could have a quick look. Thanks :)

**Comment by Erotemic** [comment]
Sure,

So, it looks like (in retrospect it turns out that this is not true) your GPG keys are being imported correctly. I see: 

```
pub   ed25519 2020-01-07 [SC] [expires: 2021-01-06]
      62C4486CBDEA6B757F9B8AD5E55B7D77B574D823
uid           [ultimate] ankurankan-CI-Key (This key is for signing releases on CI servers) <ankurankan@gmail.com>
sub   cv25519 2020-01-07 [E] [expires: 2021-01-06]
``` 

which indicates the decryption of the keys was successful. 

I do see an error on the line 

```
MB_PYTHON_TAG=$(python -c "import setup; print(setup.MB_PYTHON_TAG)")
```

because the setup file doesn't have a MB_PYTHON_TAG, but this is only relevant if building manylinux binary wheels, so we could fix this by setting the line to `MB_PYTHON_TAG=py3-none-any` instead, but I don't think this isn't causing the issue. However, it would be good to fix. 

It looks like the wheels and tarfiles are building fine.

It looks like there is an issue when signing the gpg-wheels. It says 

```
gpg: skipped "B574D823": No secret key
gpg: signing failed: No secret key
```

However, that suffix does match the key reported by gpg earlier. 

-------

So, its saying that there is no secret key. I'm going back and checking if the secret key really did import. Looking at it it looks like there was an issue importing the secret key: 

```
0.04s$ TSP=$CI_GITHUB_SECRET openssl enc -aes-256-cbc -md MD5 -pass env:TSP -d -a -in dev/travis_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import
gpg: key E55B7D77B574D823: "ankurankan-CI-Key (This key is for signing releases on CI servers) <ankurankan@gmail.com>" not changed
gpg: key E55B7D77B574D823/E55B7D77B574D823: error sending to agent: No pinentry
gpg: key E55B7D77B574D823/76D940FF80E740DF: error sending to agent: No pinentry
gpg: error reading '[stdin]': No pinentry
gpg: import from '[stdin]' failed: No pinentry
gpg: Total number processed: 0
gpg:              unchanged: 1
gpg:       secret keys read: 1
```

Its saying No pinentry. Perhaps you used a password when you created your GPG key? In that case the server might be trying to request a pin, but because it is headless it is failing. If you did create your key with a password, then I would try making one without a password (that's what I've done in the past, which is why I haven't seen this error before). 

If you need to push up a release sooner rather than later, it is also possible to disable gpg signing for now. You could do this by flipping the `USE_GPG=True` to `USE_GPG=False` in the `.travis.yml`. This would let you ensure that publishing works, and then you could go back and fix the gpg issue afterwords.

**Comment by ankurankan** [comment]
@Erotemic Thanks a lot. You are right, I used a password to create the key. I will try to generate a new one without the password.

**Pull request merged**
