### PR TITLE
MLE: Fix missing CPD columns

### PR DESCRIPTION
**Pull request by chrisittner**
Fix for a bug in `MaximumLikelihoodEstimator.get_parameters()`, reported in #352, #573 and #579. See my [comment](https://github.com/pgmpy/pgmpy/issues/579#issuecomment-196003936) for explanation.

Additionally changed some docstrings, they weren't saying the truth :).

### CODE REVIEW

**Comment by chrisittner** [comment]
plus basic test for MLE

**Comment by yashu-seth** [comment]
@chrisittner There are other cases for which more tests can be added. I just opened an issue #668 . If you want, please have a look at it.

**Comment by chrisittner** [comment]
@yashu-seth good! I also noticed tests were missing, but here I just included a test for this specific bug. I won't work on #668 this or next week, but might do it if it is still around later on.

**Comment by yashu-seth** [comment]
@chrisittner Cool.

**Pull request merged**
