### PR TITLE
Fixes issue #780

### PR DESCRIPTION
**Pull request by yashu-seth**
#780

### CODE REVIEW

**Comment by yashu-seth** [comment]
@ankurankan @khalibartan @Chriskamphuis I found the problem in the reduce methods. The values were being sorted according to variable indices. Hence, it was giving correct output only when the input parameter was sorted according to the variables. 
With @Chriskamphius' [example](https://gist.github.com/ankurankan/3077a0b0cffa7c733790d55eb83028b7) every new instance created a new order of variables for ```JointGaussianDistribution``` but the input parameters of the reduce method remained same. 
Reviews please.

**Comment by yashu-seth** [comment]
@Chriskamphuis Do you know the correct result for your example?

**Comment by chriskamphuis** [comment]
@yashu-seth 
Not for this example, I have another example that I have the solution for. I can test it with that example if you want?

**Comment by yashu-seth** [comment]
@Chriskamphuis Yeah sure. Just keep in mind that the current dev branch has a slight change in ```LinearGaissianCPD``` API. You can have a look at its API doc. If you want may be we can add you examples as tests.

**Comment by chriskamphuis** [comment]
@yashu-seth Okay, I can write some tests later this week if that is ok with you? Today I am a bit busy, but I think I can add 2 or 3 tests.

**Comment by yashu-seth** [comment]
@Chriskamphuis Okay. Just let me know the results when you verify this with your known solution.

**Comment by chriskamphuis** [comment]
@yashu-seth Hmm, I now see I only have an example for a JGD that was not derive from a linear Bayesian network. I can send you that data, I do not now if that is sufficient enough for you?

**Comment by yashu-seth** [comment]
@Chriskamphuis I don't think that would be sufficient. Anyways you can share it.

**Comment by ankurankan** [comment]
@yashu-seth You can compute something by hand and then use that to test. Shouldn't be too difficult I think.

**Comment by yashu-seth** [comment]
@ankurankan The hand computed tests are already there. I also added few tests to ensure the problem is fixed. I thought maybe if we can get the solution for the Chriskamphuis' example it would be great. But since we don't have it, the current tests should suffice.

**Pull request merged**
