### PR TITLE
creates DataFrame object to remove pandas dependency

### LINKED ISSUE #594: Remove pandas dependency
We are using pandas just to keep a track on which column of the array correspond to which variable. 
For example in the case of sampling we return a pandas dataframe with the samples generated. Something like this:

``` python
    A    B    C
0   1    0    1
1   0    0    1
2   1    1    1
.....
```

We should replace it with just a numpy array and a list of variable names. We can define an object which has two properties `variables` and `values`. Something like this:

``` python
sampling_results.variables = ['A', 'B', 'C']
sampling_results.values = [[1, 0, 1],
                           [0, 0, 1],
                           [1, 1, 1]
                           ....    ]
```

### PR DESCRIPTION
**Pull request by yashu-seth**
Fixes #594 #579

### CODE REVIEW

**Comment by yashu-seth** [comment]
@ankurankan Please have a look at this. If things are fine I will start replacing pandas dataframe with pgmpy DataFrame.

**Comment by yashu-seth** [comment]
@ankurankan Please have a look at this. If things are fine I will start replacing pandas dataframe with pgmpy.DataFrame.

**Comment by yashu-seth** [comment]
@ankurankan I'll add an add_samples method and any other method that would be necessary while replacing panadas dataframe.

**Comment by ankurankan** [comment]
@yashu-seth Give me some time on this. Need to think the best way for doing this.

**Comment by yashu-seth** [comment]
Ok.

**Comment by yashu-seth** [comment]
@ankurankan Can you tell me a bit about what you have in mind with this?

**Comment by khalibartan** [comment]
@ankurankan What implementation you have in mind ?

**Comment by ankurankan** [comment]
Ref #703

**Pull request closed without merging**
