### PR TITLE
Solve Bug in Doc of BayesianModel

### PR DESCRIPTION
**Pull request by Ashutosh-Adhikari**
Bug in Examples of is_active_trail() and get_independencies()

### CODE REVIEW

**Comment by khalibartan** [comment]
@Ashutosh-Adhikari You should read this, https://github.com/pgmpy/pgmpy/blob/dev/Contributing.md, especially forks + github pull requests section. This will help you understanding git work flow. You shouldn't merge you own changes, and shouldn't send a PR from your dev branch. Feel free to ask for any help.

**Comment by khalibartan** [comment]
@ankurankan MRG +1 from my side

**Comment by Ashutosh-Adhikari** [comment]
Well thank you @khalibartan ...
I'll make a new PR?

**Comment by khalibartan** [comment]
@Ashutosh-Adhikari There is no need for that. If you are now comfortable with git, what you can do is that rebase over your commit history , squash these commits into one. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History this link might help. There is no necessity , do this if you fell comfortable .

**Comment by yashu-seth** [comment]
@Ashutosh-Adhikari You can have a look at this [learn-git](https://github.com/yashu-seth/learn-git) or [git-workflow](https://github.com/asmeurer/git-workflow). These may help you.

**Comment by Ashutosh-Adhikari** [comment]
Thank You @yashu-seth  , @khalibartan

**Comment by ankurankan** [comment]
@Ashutosh-Adhikari Please squash your commits in one using `rebase`. Here's a tutorial on how to: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Pull request merged**
