### PR TITLE
to_tabular_cpd method of TreeCPD [refs #200]

### PR DESCRIPTION
**Pull request by palashahuja**

### CODE REVIEW

**Comment by ankurankan** [comment]
@palashahuja What's with two different PRs?

**Comment by palashahuja** [comment]
@ankurankan  I have combined all the changes into a single PR

**Comment by ankurankan** [comment]
@palashahuja Still failing.. And also please merge the latest `dev` branch to your branch and resolve merge conflicts.

**Comment by palashahuja** [comment]
@ankurankan The merge conflict was due to small error in the change of the test cases. I have corrected the error now, So please have a look.

**Comment by ankurankan** [comment]
@palashahuja Can you please add docstrings and doctests for this method? Also merge in the latest dev and resolve the merge conflicts.

**Comment by ankurankan** [comment]
Waiting on https://github.com/pgmpy/pgmpy/pull/358 for `parent_order`.

**Pull request closed without merging**
