### PR TITLE
Changed broken heart to heart in PR template

### PR DESCRIPTION
**Pull request by khalibartan**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Changes
Please list the proposed changes in this pull request.
- Changed broken heart to heart in PR template

💔Thank you!

### CODE REVIEW

**Comment by ankurankan** [comment]
@khalibartan I think it would be the best to remove all the emojis. Could you please do that ? Thanks :)

**Comment by khalibartan** [comment]
@ankurankan Done.

**Comment by ankurankan** [comment]
@khalibartan Also could you please rebase your branch on latest dev ?

**Comment by khalibartan** [comment]
@ankurankan Done

**Review by ankurankan — APPROVED** [review]

**Pull request merged**
