### PR TITLE
Structure learning continuous data [#772]

### PR DESCRIPTION
**Pull request by harishkashyap**
### Your checklist for this pull request
Implements learning continuous data parameters.

### Fixes # . (if there is no issue for this, please create one)
- Adds MLE support
- Adds Example

#### Changes
- Changes original structure of Linear Gaussian CPD parameters.
This is because beta and sigma can be latent variables that may have to be estimated if not known. 
- 

Thank you!

### CODE REVIEW

**Comment by harishkashyap** [comment]
@ankurankan could someone take a look at this and review it? I need to talk about this soon at london odsc.

**Comment by ankurankan** [comment]
@harishkashyap Thanks for the PR. I will try to merge this tonight. In the meanwhile, could you please rebase your branch over `dev`? Github is showing your branch to be out-of-date.

**Comment by harishkashyap** [comment]
Thanks @ankurankan , there are some optimizations that needs to be done that I am aware of (such as an efficient computation of the symmetric matrix), but I want you to review the architecture before that.

**Comment by ankurankan** [comment]
@harishkashyap Looks good. A few minor things that I would like to point out are:
1. To remove all the `print` statements from the code.
2. Follow PEP8 (https://www.python.org/dev/peps/pep-0008/)

Just let me know when you are done with all your changes.

**Comment by harishkashyap** [comment]
@ankurankan should be ready.

**Review by ankurankan — APPROVED** [review]

**Comment by ankurankan** [comment]
@harishkashyap Thanks for the PR. I did some minor changes for docs to look better.

**Pull request merged**
