### PR TITLE
fixed normalize method of TabularCPD

### LINKED ISSUE #635: Repeated use of reduce and marginalize on same TabularCPD produces errors
If I repeatedly call reduce or marginalize on the same tabular CPD using different variables I get an error. I don't think this behavior is expected as I think reducing a CPD in one single call to reduce by providing all the variables and repeatedly calling reduce separately for each variable should produce the same output.

``` python
c = TabularCPD('grade', 3, [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                             [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                             [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]],
...                                evidence=['intel', 'diff'], evidence_card=[3, 2])
>>> c.reduce([('intel', 0), ('diff', 0)])
>>> print(c)
+---------+---------+
| intel   | intel_0 |
+---------+---------+
| diff    | diff_0  |
+---------+---------+
| grade_0 | 0.1     |
+---------+---------+
| grade_1 | 0.1     |
+---------+---------+
| grade_2 | 0.8     |
+---------+---------+

>>> c = TabularCPD('grade', 3, [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                            [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                            [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]],
...                               evidence=['intel', 'diff'], evidence_card=[3, 2])


>>> c.reduce([('diff', 0)])
>>> c.reduce([('intel', 0)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmpy/factors/CPD.py", line 348, in reduce
    super(TabularCPD, tabular_cpd).reduce(values)
  File "pgmpy/factors/Factor.py", line 432, in reduce
    phi.values = phi.values[tuple(slice_)]
IndexError: too many indices

```

It is the same case with `marginalize` method.

### PR DESCRIPTION
**Pull request by anaviltripathi**
Fixes #635.

### CODE REVIEW

**Comment by anaviltripathi** [comment]
I have fixed the bug with the normalize method that prevented using `reduce`, `marginalize` multiple number of times and was outright wrong. 
I still have qualms about allowing `reduce` and `marginalize` methods to take the main variable itself as parameter for inplace reduction/marginalization.

**Comment by khalibartan** [comment]
+1.

**Comment by yashu-seth** [comment]
@anaviltripathi Have you added or fixed tests for the changes?

**Comment by anaviltripathi** [comment]
@yashu-seth No, I haven't added any more cases. Old cases were fine but a lot of corner cases could be added.

**Comment by yashu-seth** [comment]
@anaviltripathi If you feel so please add them.

**Comment by anaviltripathi** [comment]
@yashu-seth A lot of corner cases to a many methods of TabularCPD can and should be added. As @khalibartan has already mentioned this in #590, I ignored it here.
Currently most of the test cases use symmetric CPDs which I think should be changed. I can work on this if @khalibartan hasn't already started. I can add test cases pertaining to this fix as part of overall test fixes, or I can add it here only. 
As you say.

**Comment by yashu-seth** [comment]
@anaviltripathi I think test cases related to this fix should be added here only.
And if you want you can add more corner cases for normalize. Just get it confirmed with @khalibartan.

**Comment by khalibartan** [comment]
@anaviltripathi I haven't started, but @mvnnn was interested in working on test for factor classes. You can ask him if he has any progress or you guys can distribute the work.  Also for test case IMO a different PR would better, but tests for changes related to it should be added here.

**Comment by anaviltripathi** [comment]
@ankurankan I am now using the newly added `copy` method in the `normalize` method. So, I rebased this branch on dev. If the commit history is fine this can be merged I think. Otherwise let me know what I should do.

**Comment by anaviltripathi** [comment]
@ankurankan Read a little about rebasing and I have done exactly the thing one should not do. Ignore this PR. I will send a new one.

**Comment by yashu-seth** [comment]
@anaviltripathi You can still use this PR. You can undo git rebase as well.
Google git reflog, it will be useful.

**Comment by anaviltripathi** [comment]
@yashu-seth I already created a new PR. But thanks, it will be useful in the future.

**Pull request closed without merging**
