### PR TITLE
Implementing Hash for IndependenceAssertion and reduce method

### PR DESCRIPTION
**Pull request by aelnouby**
Used different Hash function than that in #640 
`return (hash(frozenset(self.event1))<<1)^(hash(frozenset(self.event2))>>1)^hash(frozenset(self.event3))
`
 Now the order of the events will produce different hash and tested it against the case @khalibartan proposed ( X_|_ Y,Z | W) and (Z,Y_|_X | W)

### CODE REVIEW

**Comment by aelnouby** [comment]
There is a problem , currently fixing

**Comment by khalibartan** [comment]
@aelnouby This is not good, there are already PR that deals with this issue, #536 #640 .

**Comment by aelnouby** [comment]
@khalibartan I am sorry if this caused any problems , but things aren't very clear #536 has been open for a long time and your last comment was a recommendation to close it , #640 i have just changed the hashing function in order to get the desired behaviour  , so please tell me what is the best practise in cases such like this.

**Comment by khalibartan** [comment]
@aelnouby If you want to have a particular implementation , you can discuss it with the user, who is currently working on it. Like if you wanted to be hash function like this it would have been good if you discussed it over #640 thread . Let see what @ankurankan has to say about it. But in my view it is waste of efforts of both developers.

**Comment by ankurankan** [comment]
@aelnouby Can you please create an issue for the problem you were facing when you were working with changes from #640 ?

**Comment by aelnouby** [comment]
@ankurankan i just want to understand a few things , first right now the merged #640 , i can't see how the duplication problem was solved.

Secondly, right now what i implemented is a hash method that will produce different hashes to different independencies whatever the order is , and implemented the reduce method (using a set) to remove duplication.

The problems i faced happened when i tried to get rid of the reduce method and prevent duplication form the beginning by making Independencies a set (you can imagine this might need some modifications to happen in many places ), when i referred to #640 in this problem, i  was referring to a commit that dealt with a similar problem but it was removed later.

I didn't spend much time trying to solve this problem , but if making independencies a set is required, i will work on it and i will report if i faced any problems.

**Comment by khalibartan** [comment]
@aelnouby The `__hash__` should return similar hash values for `(X _|_ Y,Z | W)` and `(Z,Y _|_ X | W)`, I never meant that they should return different hash values. If you properly read the context at [here](https://github.com/pgmpy/pgmpy/pull/640#discussion_r53423413) you will understand that I was implying that if represent Independencies (not IndependenceAssertion) as a set than we will remove such cases without users knowledge. It should be reduce function that removes all the similar assertions.

**Comment by aelnouby** [comment]
@khalibartan Thanks i get it now , i misunderstood what you meant. 

So is there is anything more to do concerning this issue , or should it be closed.

**Comment by khalibartan** [comment]
@aelnouby First @ankurankan needs to define what he wants from reduce method. Two things come in my mind:
- When independencies are `(X _|_ Y,Z | W )` , `(Y,Z _|_ X | W)` and `(X _|_ Y | W )`, should it return `(X _|_ Y,Z| W)` because first and second are equivalent and third one assert a independence that is asserted by first and second.
- Or should it return `(X _|_ Y,Z | W)` and `(X _|_ Y | W )`.

If it is the second case then nothing needs to be done.

**Comment by ankurankan** [comment]
@aelnouby @khalibartan I was thinking that reduce should return the least number of assertions. So reducing these: `(X _|_ Y,Z | W )` , `(Y,Z _|_ X | W)` and `(X _|_ Y | W )` should return `(X _|_ Y, Z | W)`.

**Comment by khalibartan** [comment]
@ankurankan I think we can either have a naive level implementation that utilises subset checking for events or we can use the changes of #636 . What would you prefer ? Or any other implementation.

**Comment by chrisittner** [comment]
(With the methods from #636 you can implement `reduce` to remove all redundancy, but it is probably too slow. I will work on #636 some more in the next days and check performance on larger models + asymptotic complexity, for now i don't know. But `reduce` should be fast, because it gets called by `BayesianModel.get_independencies()` etc.)

**Comment by khalibartan** [comment]
I believe this can be closed for now.

**Comment by aelnouby** [comment]
fixed in #636

**Comment by khalibartan** [comment]
@aelnouby Since you are looking to work with some thing, may be you can work with some read write classes #65 .Parsing formats is pretty easy task, just search for the semantics for particular file format and ping ankur before working on it. If you find any issues while working ping me over the thread.

**Comment by aelnouby** [comment]
@khalibartan Great i will start with the DBN copy method in #489 and then i will have a look at this. I will also wait for ankur's response concerning the score and cross validation additions.

Also may you recommend for me issues that might be related or can help me with the ADD project , as an entrance task for this project ?

Thanks a lot for your help :D

**Comment by khalibartan** [comment]
@aelnouby I cannot comment on this matter.
Since you are working with DBN class, I would like if you could do some cleaning, also there are quite some `#TODO:` marked in it and some issues at here #557 #452 , fix them too.

**Pull request closed without merging**
