### PR TITLE
exactInference test added for markov model

### PR DESCRIPTION
**Pull request by anaviltripathi**
I have basically used the same graph as for the Bayesian network with small modification of moralization. Tell me if something is wrong or missing.

### CODE REVIEW

**Comment by khalibartan** [comment]
@anaviltripathi The practice you have followed is depreciated. You shouldn't send a PR from your dev branch. Also changes related to different issues must be solved in separate PR. It helps admins and collaborators in reviewing process.

**Comment by ankurankan** [comment]
@anaviltripathi The best way to work on multiple separate features at the same time is to work on multiple separate branches each for a feature. That will allow you to send separate PRs and keep your changes for different features separate. You can also read this: http://nvie.com/posts/a-successful-git-branching-model/ and we usually try to follow this. 

What you can do now is to create separate branches for each feature and then cherry-pick (https://git-scm.com/docs/git-cherry-pick) these commits into respective branches and then create new PRs from those branches.

**Comment by anaviltripathi** [comment]
@khalibartan @ankurankan Thanks, will keep this in mind. I am sending new PRs.

**Comment by khalibartan** [comment]
@anaviltripathi Close this.

**Comment by anaviltripathi** [comment]
Closing as it is useless now.

**Pull request closed without merging**
