### PR TITLE
Add Marginal Inference for undirected models.

### PR DESCRIPTION
**Pull request by jakee417**
### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [X] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [X] Check the commit's or even all commits' message styles matches our requested structure.

### Issue number(s) that this pull request fixes
- N/A

### List of changes to the codebase in this pull request
- Adds `MarginalEstimator` as a base class for all marginal based estimation.
- Adds `MirrorDescentEstimator` inspired from [this](https://github.com/ryan112358/private-pgm/blob/master/src/mbi/inference.py) repo.
- Adds a `FactorDict` as an analog to the `FactorSet`. Includes functions for basic operations between two `FactorDicts`.
- Gives `ClusterGraph` a `clique_beliefs` (`FactorDict`) property.
- Adds appropriate unit testing.

### CODE REVIEW

**Comment by ankurankan** [comment]
@jakee417 Thanks a lot for the PR. I will try to review it ASAP, but might take me some time.

**Comment by jakee417** [comment]
> @jakee417 Thanks a lot for the PR. I will try to review it ASAP, but might take me some time.

Yes understandable, its quite a large PR. Perhaps we can do this:

1) Quick scan of the high level design -> give me feedback of whether you want this in pgmpy at all.

If so then,

2) Cancel this PR
3) PR for MarginalEstimator + FactorDict + unit tests
4) PR for MirrorDescentEstimator + unit tests
5) PR for the football example showing usage end to end.

Let me know your preference @ankurankan, personally I think a way to estimate undirected models is a nice addition to this library. `FactoredInference` in [Private-pgm](https://github.com/ryan112358/private-pgm) is one such way to do this, which I have offered in this design.

**Comment by ankurankan** [comment]
@jakee417 Sorry again for so much delay in reviewing. I had a quick look and looks good to me. I will merge this for now. I did notice that it throws an error when using the torch backend. It would be nice to add tests for testing both numpy and torch backends (something like https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_estimators/test_MaximumLikelihoodEstimator.py).

**Comment by jakee417** [comment]
I can follow up with the Torch errors, was not aware there was a PyTorch backend 😅

**Pull request merged**
