### PR TITLE
error in to_factor_graph() function in pgmpy/models/MarkovModel.py 

### PR DESCRIPTION
**Pull request by VSSILPA**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Changes
In MarkovModel.py, Line no.295, in to_factor_graph() function, factor_graph.add_edges_from(itertools.product(scope, [factor_node])),
factor_node changed to factor since factor_node is of type <class 'str'>, but the edge in factor_graph should be from a variable node to a factor_node of  type  <class 'pgmpy.factors.discrete.DiscreteFactor.DiscreteFactor'>.

💔Thank you!

### CODE REVIEW

**Comment by khalibartan** [comment]
@VSSILPA By mistake, you have created a new file by changing the path structure. You have to make changes to this [file](https://github.com/VSSILPA/pgmpy/blob/ee839245c47e41d7a2c8c09dac6bee5de9fce6ce/pgmpy/models/MarkovModel.py) in your branch `(the correct path is pgmpy/models/MarkovModel.py if you are in the root directory)`. Also, you will have to make some changes in markov model tests to accommodate these changes

**Comment by VSSILPA** [comment]
I think I messed it up. Not used to git,Can I issue a new pull request? Sorry for the incovenience caused.

**Comment by khalibartan** [comment]
@VSSILPA No problem :D . You can refer [git book](https://git-scm.com/book/en/v2). First 3 chapters are more than enough to help you out in most of the cases or you can ask our help too. Please also make sure that you add test cases for these changes. Old test cases shouldn't have passed.

Another note: A general advice please name your branch meaningfully, it will help you identify branches in case you are working on many branches simultaneously.

**Comment by VSSILPA** [comment]
Thank you. Can you please give information on how and where to add test cases for the changes made? Actually I don't have idea how to do it. That's why I had to leave that part.

**Comment by khalibartan** [comment]
@VSSILPA You can have a look at corresponding test cases at [here](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_models/test_MarkovModel.py#L211)

**Pull request closed without merging**
