### PR TITLE
Fixed issues with networkx 1.9.1

### PR DESCRIPTION
**Pull request by pratyakshs**
Output of `nosetests3`:
`$ nosetests3`
`.....................................................................................SSS....................................................................................``...................................................../home/pratyaksh/workspace/gsoc/pgmpy/pgmpy/readwrite/PomdpX.py:359:``FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is``not None' test instead.`
 `if parameter.find('SubDAGTemplate'):`
`...............................`
`----------------------------------------------------------------------`
`Ran 256 tests in 2.660s`

`OK (SKIP=3)`

### CODE REVIEW

**Comment by abinashpanda** [comment]
@pratyakshs Thanks for looking into this issue. I have only one concern with your hack, every time you add an edge using `add_edge` method it would create a `DiGraph` object which for larger graphs would not only be time-intensive, it would be also memory-intensive. If you could find some cleaner solution that would be better.

**Comment by pratyakshs** [comment]
@abinashpanda I agree with your point. But well, isn't cycle detection running in O(V+E) for each add_edge call?

**Comment by abinashpanda** [comment]
@pratyakshs I am not worried about the time taken for cycle detection, my concern is regarding creating new objects in each iteration. I am against object creation.

**Comment by pratyakshs** [comment]
@abinashpanda There's another way to do almost the same thing. Instead of passing `nx.DiGraph(self)` as argument, we can instead pass `type(nx.DiGraph())(self)` which is basically a typecast. Does it fit the bill?

**Comment by abinashpanda** [comment]
@pratyakshs This would also cause the same issue of creation of `DiGraph` objects. Have a look at the code sample

``` python
In [1]: import networkx as nx

In [2]: a = nx.DiGraph([('a', 'b'), ('c', 'd')])

In [3]: a
Out[3]: <networkx.classes.digraph.DiGraph at 0x7fbb343c5a90>

In [4]: b = type(nx.DiGraph())(a)

In [5]: b
Out[5]: <networkx.classes.digraph.DiGraph at 0x7fbb343cff28>
```

See the objects `a` and `b` are totally different objects stored at different memory location. There is no such typecasting over here. So if you still use `type(nx.DiGraph())(self)` it would create still create new `DiGraph` objects.

**Comment by pratyakshs** [comment]
@abinashpanda Thanks for pointing that out. I wasn't myself convinced when I wrote that!

**Comment by pratyakshs** [comment]
@abinashpanda If the issue is only with the function call `nx.simple_cycles()`, I think it would be better to write a simple code for reachability of node `u` from node `v` when an edge `(u, v)` is added. The implementation of `nx.symple_cycles` uses Tarjan's SCC algorithm (after making a copy of the original graph), then tries to find all simple cycles iteratively using these components. This looks a bit overkill (and memory intensive too) for every `add_edge` operation. Would you be interested if I add the code for reachability(BFS/DFS)?

**Comment by abinashpanda** [comment]
@pratyakshs my suggestion is keep the code as it is (as it working). If you still think that you can create a robust method for finding edges then surely go for it. Send a PR and lets review :)

**Pull request closed without merging**
