### PR TITLE
Modified query

### PR DESCRIPTION
**Pull request by raghavg7796**
I have modified query method to accept ('A', 0) and give the answer in a dictionary with key as ['A_0'].

### CODE REVIEW

**Comment by raghavg7796** [comment]
Please can someone explain me why these tests got failed.!

**Comment by raghavg7796** [comment]
My PR on asking infer.query(['A', ('B', 0), 'C', ('A', 0)]), it will give result in a dict as 
dic['A'] = Discrete Factor, dic['C'] = Discrete Factor for A, dic['B=0'] = Discrete Factor with one value..
Should I have a better input/output format...and what in case of tuple variables??

**Comment by yashu-seth** [comment]
@raghavg7796 I think the keys should be not be in the format 'B=0' but only 'B'. Only difference will be that the factor having B must be reduced  on ('B', 0).

@ankurankan I hope this isn't what you also intended.

**Comment by yashu-seth** [comment]
@raghavg7796 @ankurankan The DBN inference tests are failing. We need to do something about this tuple problem.

**Comment by yashu-seth** [comment]
@raghavg7796 A test related to state names is also failing. I know the reason. Complete this query modification first and then we will discuss it.

**Comment by raghavg7796** [comment]
@yashu-seth @ankurankan For case of tuple handling, we can make a new query method like val_query or query_with_val

**Comment by ankurankan** [comment]
@raghavg7796 @yashu-seth I am not in the favor of having a new method for this. Let's hold this PR till we have a better idea.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth My nostests are passing except for 3 where they can't find mock. Why here tests are failing? I have added support for tuple variables. Please review my PR.

**Comment by yashu-seth** [comment]
@raghavg7796 The state name test is failing because it does not account for the case when the parameter to be mapped should be returned as it is. Which could be a case here because for inputs like ```['A', 'B']``` no mapping is required. You can look into the state_name file yourself to fix this. In case you have problems, just let me know.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth I fixed the errors. 1 more problem remains what if user asks 2 value_queries with 1 variable like query([('A', 0), ('A', 1)])? What to do in that case when user asks multiple queries for a single variable.?

**Comment by yashu-seth** [comment]
@raghavg7796 I can't find a good solution for this. If you remove the state name decorator it won't work for the user defined states.
You asked me about the state name error so I told you about it, but I also believe this PR should be held until we find a better solution.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth I have implemented the case of user defined states. You can see the lattest commit. It handles the case of user defined states as well as internal states. Infact, everything is working fine, I just need to see what output will be given in case of multiple queries on same variable(may be a factor product).

**Comment by ankurankan** [comment]
Closing this as we don't have a proper solution for this right now. Possible solutions can be discussed in #779

**Pull request closed without merging**
