### PR TITLE
removed local imports

### PR DESCRIPTION
**Pull request by sandeepkrjha**
Fix issue #546 .

### CODE REVIEW

**Comment by yashu-seth** [comment]
@sandeepkrjha You can have a look at [this](http://stackoverflow.com/questions/273695/git-branch-naming-best-practices). Giving relevant names to your branch always helps in keeping things less chaotic.

**Comment by khalibartan** [comment]
@sandeepkrjha I believe these changes are going to break the things. Have you run the nosetests in your local branch. Cyclic imports will raise an error.Not all of the local import statements were to be removed (see the discussion in #546 ) . Send in a new commit. Also relable the pull request and add a better commit message. Refer our contributing guide for basic helps, also feel free to ask . https://github.com/pgmpy/pgmpy/blob/dev/Contributing.md

**Comment by sandeepkrjha** [comment]
@yashu-seth I am a newbie on open source platform. I will name the branch carefully from next time.

**Comment by yashu-seth** [comment]
@sandeepkrjha No problem. I hope you understood @khalibartan 's suggestions. Please feel free to ask any queries.

**Comment by OrkoHunter** [comment]
Local imports are not going to cause circular import problem if the best import guidelines are followed.
- [PEP 328](https://www.python.org/dev/peps/pep-0328/)
- [Google Code Styleguide](https://google.github.io/styleguide/pyguide.html#Imports)

The problem does not lie in importing the modules, but in importing any name from the module. If import styles are being changed, I believe it should be changed to the best.

**Comment by khalibartan** [comment]
@OrkoHunter Yeah. If we import  for eg like this `models.BayesainModel` instead of `BayesainModel`, the former will not cause circular import problem . I do know that. But I don't think that has been followed .

**Comment by ankurankan** [comment]
@sandeepkrjha There are merge conflicts. You will have to rebase your changes over the latest dev. Also your changes are resulting in circular import. You will need to fix that.

**Comment by khalibartan** [comment]
@sandeepkrjha are you still working on it ?

**Comment by ankurankan** [comment]
Closing as not active anymore.

**Pull request closed without merging**
