### PR TITLE
Adds Markov Blanket to Bayesian Models

### PR DESCRIPTION
**Pull request by harishkashyap**
#### Changes
* Added Markov Blanket to Bayesian Models

### CODE REVIEW

**Comment by harishkashyap** [comment]
@ankurankan , I thought of adding get_markov_model but I saw that markov_model has the blanket implemented otherwise (http://pgmpy.org/_modules/pgmpy/models/MarkovModel.html) and hence had it for uniformity. Anycase, have made that change. The tests are also updated.

**Comment by ankurankan** [comment]
@harishkashyap We would like to have only 2 commits for this. One with the children method and it's tests and the second for the markov blanket and it's tests. We want to keep each commit for a specific feature so that it's easier to rollback in future if required. Also, we don't want any merge commits. So, I would suggest you to start with a new branch off the pgmpy:dev, and add your changes and do a couple of commits on that and create a new PR from the new branch.

**Comment by harishkashyap** [comment]
Makes sense. Would rebasing —fondly with two commits make sense? First one being the children method and second commit being the blanket? That way we can only a single PR and you can always roll back to a feature?

**Comment by harishkashyap** [comment]
Sorry autocorrect. I meant —ff-only and I can put up a single PR with two commits in order by rebasing

**Comment by ankurankan** [comment]
@harishkashyap Thanks. Closing this since duplicate of #959

**Pull request closed without merging**
